/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_victorcruz;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor Jafet Cruz
 */
public class MAIN extends javax.swing.JFrame {

    /**
     * Creates new form MAIN
     */
    public MAIN() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JTP_REPORTE = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTF_Username = new javax.swing.JTextField();
        JPF_Password = new javax.swing.JPasswordField();
        JB_IniciarSesion = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_1 = new javax.swing.JTable();
        JB_MOD_LIBRO = new javax.swing.JToggleButton();
        JB_ELI_LIBRO = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_2 = new javax.swing.JTable();
        JB_MOD_PER = new javax.swing.JToggleButton();
        JB_ELI_PER = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTF_PN = new javax.swing.JTextField();
        JTF_PA = new javax.swing.JTextField();
        JFT_EDAD = new javax.swing.JFormattedTextField();
        JB_RegistrarU = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        JFF_Codigo = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        RB_ADMIN = new javax.swing.JRadioButton();
        RB_User = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        JTF_titulo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JTF_autor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JTF_editorial = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JTF_aIngre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        JTF_idioma = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JFF_ISBN = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        RB_Disp = new javax.swing.JRadioButton();
        RB_pres = new javax.swing.JRadioButton();
        RB_fueraIn = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        JTF_numCuenta = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        JTF_Pre = new javax.swing.JTextField();
        JB_AGREGAR = new javax.swing.JToggleButton();
        jLabel19 = new javax.swing.JLabel();
        JTF_ACREa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        JTF_GENERO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EXAMEN 1 Victor Cruz");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME: ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD: ");

        JPF_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPF_PasswordActionPerformed(evt);
            }
        });

        JB_IniciarSesion.setText("INICIAR SESION");
        JB_IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_IniciarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JB_IniciarSesion)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JTF_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JPF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTF_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JPF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(JB_IniciarSesion)
                .addGap(65, 65, 65))
        );

        JTP_REPORTE.addTab("LOGIN", jPanel2);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        Table_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Autor", "Titulo", "Estado", "Año de Creacion", "Editorial", "ISBN", "Estado", "Idioma", "numero de cuenta", "persona prest"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table_1);

        JB_MOD_LIBRO.setText("MODIFICAR");
        JB_MOD_LIBRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_MOD_LIBROActionPerformed(evt);
            }
        });

        JB_ELI_LIBRO.setText("ELIMINAR");
        JB_ELI_LIBRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ELI_LIBROActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(JB_MOD_LIBRO)
                        .addGap(58, 58, 58)
                        .addComponent(JB_ELI_LIBRO)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_MOD_LIBRO)
                    .addComponent(JB_ELI_LIBRO))
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("LIBROS", jPanel6);

        Table_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Primer Nombre", "Primer Apellido", "Codigo", "Edad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Table_2);

        JB_MOD_PER.setText("MODIFICAR");
        JB_MOD_PER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_MOD_PERMouseClicked(evt);
            }
        });

        JB_ELI_PER.setText("ELIMINAR");
        JB_ELI_PER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_ELI_PERMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JB_MOD_PER)
                    .addComponent(JB_ELI_PER))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(JB_MOD_PER)
                        .addGap(39, 39, 39)
                        .addComponent(JB_ELI_PER)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PERSONAS", jPanel7);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        JTP_REPORTE.addTab("REPORTE", jPanel4);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRIMER NOMBRE:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRIMER APELLIDO:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EDAD: ");

        JTF_PA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_PAActionPerformed(evt);
            }
        });

        JFT_EDAD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####-"))));

        JB_RegistrarU.setText("REGISTAR USUARIO");
        JB_RegistrarU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_RegistrarUMouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CODIGO");

        try {
            JFF_Codigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("QUE TIPO DE USUARIO: ");

        RB_ADMIN.setText("ADMIN");

        RB_User.setText("USUARIO NORMAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JFT_EDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTF_PA)
                            .addComponent(JTF_PN, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(JFF_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(RB_ADMIN)
                                .addGap(35, 35, 35)
                                .addComponent(RB_User))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(JB_RegistrarU)))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JFF_Codigo)
                    .addComponent(JTF_PN, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTF_PA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RB_ADMIN)
                            .addComponent(RB_User))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JFT_EDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(JB_RegistrarU)
                .addGap(49, 49, 49))
        );

        JTP_REPORTE.addTab("USUARIO", jPanel3);

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        jLabel9.setText("TITULO:");

        jLabel10.setText("AUTOR");

        JTF_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_autorActionPerformed(evt);
            }
        });

        jLabel11.setText("Año Ingresado");

        jLabel12.setText("EDITORIAL");

        JTF_idioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_idiomaActionPerformed(evt);
            }
        });

        jLabel14.setText("ISBN");

        try {
            JFF_ISBN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel15.setText("ESTADO");

        RB_Disp.setText("DISPONIBLE");

        RB_pres.setText("PRESTADO");

        RB_fueraIn.setText("FUERA DE INVENTARIO");

        jLabel16.setText("IDIOMA");

        jLabel17.setText("Numero de Cuenta");

        JTF_numCuenta.setText("0000");

        jLabel18.setText("Persona Prestada");

        JTF_Pre.setText("-----");
        JTF_Pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_PreActionPerformed(evt);
            }
        });

        JB_AGREGAR.setText("AGREGAR");
        JB_AGREGAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AGREGARMouseClicked(evt);
            }
        });

        jLabel19.setText("A Creado");

        jLabel20.setText("GENERO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(JTF_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(JTF_aIngre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(JTF_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(JTF_GENERO, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTF_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RB_fueraIn)
                    .addComponent(JFF_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(RB_Disp)
                    .addComponent(RB_pres)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(JB_AGREGAR)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTF_ACREa, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(JTF_numCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF_Pre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(JTF_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTF_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(JTF_numCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JFF_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF_Pre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(JTF_aIngre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel12)
                                .addGap(7, 7, 7)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RB_Disp)
                                    .addComponent(JTF_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(JTF_ACREa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(RB_pres)
                                .addGap(20, 20, 20)
                                .addComponent(RB_fueraIn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(JB_AGREGAR)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTF_GENERO, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTP_REPORTE.addTab("ADMIN(LIBRO)", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(JTP_REPORTE, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(JTP_REPORTE, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPF_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPF_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPF_PasswordActionPerformed

    private void JB_IniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_IniciarSesionMouseClicked
        String usuario = JTF_Username.getText();
        if(users.contains(usuario)){
            int i = users.indexOf(usuario);
            if(((Usuario)user.get(i)).getTipo_user().equalsIgnoreCase("ADMIN")){
                JOptionPane.showMessageDialog(null, "Usuario CREADO!!!");
                JTF_Username.setText("");
                JPF_Password.setText("");
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "Usuario no valido");
        }
    }//GEN-LAST:event_JB_IniciarSesionMouseClicked

    private void JTF_PAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_PAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_PAActionPerformed

    private void JB_RegistrarUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_RegistrarUMouseClicked
try {         
        String t_user;    
        String apelli = JTF_PA.getText();
        String primN = JTF_PN.getText();
        int Ed = Integer.parseInt(JFT_EDAD.getText());
        int Code = Integer.parseInt(JFF_Codigo.getText());
        
        if (RB_ADMIN.isSelected()) {
                t_user = "ADMIN";
            } else {
                t_user = "NORMAL";
            }
        
         users.add(primN);
         
          Usuario x = new Usuario(Code, Ed, primN, apelli, t_user);
            
            if (x.getTipo_user().equals("NORMAL")) {
                Object[] newrow = {x.getPri_nom(), x.getEdad(), x.getPrim_appe(), x.getCodigo()};
                DefaultTableModel ta1 = (DefaultTableModel) Table_1.getModel();
                ta1.addRow(newrow);
                Table_1.setModel(ta1);
                
            }//fin del fin
            
            user.add(x);
            JOptionPane.showMessageDialog(this, " se agrego un usuario a la lista a la lista! ");
                 
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Algo salio mal, intente nuevamente!\nVerifique si lleno todos los campos");
        }
        
    }//GEN-LAST:event_JB_RegistrarUMouseClicked

    private void JTF_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_autorActionPerformed

    private void JTF_idiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_idiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_idiomaActionPerformed

    private void JB_AGREGARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AGREGARMouseClicked
         String a = JTF_autor.getText();
        String t = JTF_titulo.getText();
        String g= JTF_GENERO.getText();
        String idio= JTF_idioma.getText();
        String edito = JTF_editorial.getText();
        int year = Integer.parseInt(JTF_ACREa.getText());
        String ISBN= JFF_ISBN.getText();
        int a_ingre = Integer.parseInt(JTF_aIngre.getText());
        String estado="";
        if(RB_pres.isSelected()){
        estado="Prestado";
        }else if(RB_Disp.isSelected()){
        estado="Disponible";
        }else if(RB_fueraIn.isSelected()){
        estado="Fuera de inventario";
        }
        String namep=JTF_Pre.getText();
        if(namep==""){
        namep="----";
        }
        
         Libros x = new Libros(a, t, g, idio, estado, ISBN, namep, a_ingre, a_ingre, year, a_ingre);
            Object[] newrow = {x.getA_crea(), x.getA_ingrese(), x.getAutor(), x.getEditorial(),x.getEstado(),x.getGenero(),x.getISBN(),x.getIdioma(),x.getGenero()};
            DefaultTableModel ta3 = (DefaultTableModel) Table_1.getModel();
            ta3.addRow(newrow);
            Table_1.setModel(ta3);
            lib.add(x);
            JOptionPane.showMessageDialog(this, "El BoogieWoogie se agrego a la lista! ");
        
        
    }//GEN-LAST:event_JB_AGREGARMouseClicked

    private void JTF_PreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_PreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_PreActionPerformed

    private void JB_MOD_LIBROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_MOD_LIBROActionPerformed
       if (Table_1.getSelectedRow() >= 0) {
            DefaultTableModel m = (DefaultTableModel) Table_1.getModel();
            int edad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la nueva edad"));
            String nombre = (String)m.getValueAt(Table_1.getSelectedRow(), 0);
            for (int i = 0; i < user.size(); i++) {
                Usuario c = user.get(i);
                if (c.getPri_nom().equals(nombre)) {
                    c.setEdad(edad);
                }
            }
            m.setValueAt(edad, Table_1.getSelectedRow(), 1);
            Table_1.setModel(m);
            JOptionPane.showMessageDialog(null, "Se modifico exitosamente");
        }else if(Table_1.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Error. La tabla esta vacia");
        }else{
            JOptionPane.showMessageDialog(null, "Error, primero seleccione una fila");
        }
    }//GEN-LAST:event_JB_MOD_LIBROActionPerformed

    private void JB_ELI_LIBROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ELI_LIBROActionPerformed
       if (Table_1.getSelectedRow() >= 0) {
            DefaultTableModel m = (DefaultTableModel) Table_1.getModel();
            String nombre = (String)m.getValueAt(Table_1.getSelectedRow(), 0);
            for (int i = 0; i < user.size(); i++) {
                Usuario c = user.get(i);
                if (c.getPri_nom().equals(nombre)) {
                    user.remove(i);
                }
            }
            m.removeRow(Table_1.getSelectedRow());
            Table_1.setModel(m);
            JOptionPane.showMessageDialog(null, "Se elimino exitosamente");
        }else if(Table_1.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Error. La tabla no tiene contenido");
        }else{
            JOptionPane.showMessageDialog(null, "Error, primero seleccione una fila");
        }
    }//GEN-LAST:event_JB_ELI_LIBROActionPerformed

    private void JB_MOD_PERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_MOD_PERMouseClicked
       if (Table_2.getSelectedRow() >= 0) {
            DefaultTableModel m = (DefaultTableModel) Table_2.getModel();
            int edad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la nueva edad"));
            String nombre = (String)m.getValueAt(Table_2.getSelectedRow(), 0);
            for (int i = 0; i < user.size(); i++) {
                Usuario c = user.get(i);
                if (c.getPri_nom().equals(nombre)) {
                    c.setEdad(edad);
                }
            }
            m.setValueAt(edad, Table_2.getSelectedRow(), 1);
            Table_2.setModel(m);
            JOptionPane.showMessageDialog(null, "Se modifico exitosamente");
        }else if(Table_2.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Error. La tabla esta vacia");
        }else{
            JOptionPane.showMessageDialog(null, "Error, primero seleccione una fila");
        }
    }//GEN-LAST:event_JB_MOD_PERMouseClicked

    private void JB_ELI_PERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ELI_PERMouseClicked
        if (Table_2.getSelectedRow() >= 0) {
            DefaultTableModel m = (DefaultTableModel) Table_2.getModel();
            String nombre = (String)m.getValueAt(Table_2.getSelectedRow(), 0);
            for (int i = 0; i < user.size(); i++) {
                Usuario c = user.get(i);
                if (c.getPri_nom().equals(nombre)) {
                    user.remove(i);
                }
            }
            m.removeRow(Table_2.getSelectedRow());
            Table_2.setModel(m);
            JOptionPane.showMessageDialog(null, "Se elimino exitosamente");
        }else if(Table_2.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Error. La tabla esta vacia");
        }else{
            JOptionPane.showMessageDialog(null, "Error, primero seleccione una fila");
        }
    }//GEN-LAST:event_JB_ELI_PERMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton JB_AGREGAR;
    private javax.swing.JToggleButton JB_ELI_LIBRO;
    private javax.swing.JToggleButton JB_ELI_PER;
    private javax.swing.JToggleButton JB_IniciarSesion;
    private javax.swing.JToggleButton JB_MOD_LIBRO;
    private javax.swing.JToggleButton JB_MOD_PER;
    private javax.swing.JToggleButton JB_RegistrarU;
    private javax.swing.JFormattedTextField JFF_Codigo;
    private javax.swing.JFormattedTextField JFF_ISBN;
    private javax.swing.JFormattedTextField JFT_EDAD;
    private javax.swing.JPasswordField JPF_Password;
    private javax.swing.JTextField JTF_ACREa;
    private javax.swing.JTextField JTF_GENERO;
    private javax.swing.JTextField JTF_PA;
    private javax.swing.JTextField JTF_PN;
    private javax.swing.JTextField JTF_Pre;
    private javax.swing.JTextField JTF_Username;
    private javax.swing.JTextField JTF_aIngre;
    private javax.swing.JTextField JTF_autor;
    private javax.swing.JTextField JTF_editorial;
    private javax.swing.JTextField JTF_idioma;
    private javax.swing.JTextField JTF_numCuenta;
    private javax.swing.JTextField JTF_titulo;
    private javax.swing.JTabbedPane JTP_REPORTE;
    private javax.swing.JRadioButton RB_ADMIN;
    private javax.swing.JRadioButton RB_Disp;
    private javax.swing.JRadioButton RB_User;
    private javax.swing.JRadioButton RB_fueraIn;
    private javax.swing.JRadioButton RB_pres;
    private javax.swing.JTable Table_1;
    private javax.swing.JTable Table_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuario> user = new ArrayList();
    ArrayList <Libros> lib = new ArrayList();
     ArrayList users = new ArrayList();

}
